#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-.}"
cd "$ROOT"

fail() {
  echo "CURRENT VALIDATION FAILED: $*" >&2
  exit 1
}

require_file() {
  [[ -f "$1" ]] || fail "missing file: $1"
}

require_absent_path() {
  [[ ! -e "$1" ]] || fail "stale path still present: $1"
}

require_grep() {
  local pattern="$1"
  local file="$2"
  grep -Fq "$pattern" "$file" || fail "$file missing token: $pattern"
}

require_no_grep() {
  local pattern="$1"
  local file="$2"
  if grep -Fq "$pattern" "$file"; then
    fail "$file still contains removed token: $pattern"
  fi
}

require_file README.md
require_file architecture.md
require_file userguide.md
require_file CHANGELOG.md
require_file MANIFEST.txt
require_file docs/HARDWARE.md
require_file docs/MAC_DEVELOPMENT.md
require_file docs/RADIO_TUNING.md
require_file docs/RELEASE_v1.0.1.md
require_file firmware/assistant-rs/Cargo.toml
require_file firmware/assistant-rs/src/main.rs
require_file firmware/assistant-rs/src/ui_primitives.rs
require_file firmware/assistant-rs/src/ui_widgets.rs
require_file firmware/assistant-rs/src/internet_radio.rs
require_file firmware/assistant-rs/components/internet_radio_stream_shim/internet_radio_stream_shim.c
require_file firmware/assistant-rs/components/st77916_shim/st77916_shim.c
require_file firmware/assistant-rs/components/st77916_shim/include/st77916_shim.h

# Current page set.
require_grep "Home" firmware/assistant-rs/src/app/pages.rs
require_grep "Weather" firmware/assistant-rs/src/app/pages.rs
require_grep "Music" firmware/assistant-rs/src/app/pages.rs
require_grep "InternetRadio" firmware/assistant-rs/src/app/pages.rs
require_grep "Assistant" firmware/assistant-rs/src/app/pages.rs
require_grep "Settings" firmware/assistant-rs/src/app/pages.rs
require_no_grep "Video" firmware/assistant-rs/src/app/pages.rs

# Accepted radio path and UX repairs.
require_grep "STREAMBUFFER_PSRAM_PRODUCER_CONSUMER_R11_R1" firmware/assistant-rs/components/internet_radio_stream_shim/internet_radio_stream_shim.c
require_grep "xStreamBufferCreateStatic" firmware/assistant-rs/components/internet_radio_stream_shim/internet_radio_stream_shim.c
require_grep "MALLOC_CAP_SPIRAM" firmware/assistant-rs/components/internet_radio_stream_shim/internet_radio_stream_shim.c
require_grep "RADIO_UI_IDLE_OVERRIDE" firmware/assistant-rs/src/internet_radio.rs
require_grep "RAW-V1-0-1-R13-RADIO-STATION-IDLE-UI-REPAIR" firmware/assistant-rs/src/media_action_router.rs

# Accepted UI/source split.
require_grep "mod ui_primitives" firmware/assistant-rs/src/main.rs
require_grep "mod ui_widgets" firmware/assistant-rs/src/main.rs
require_grep "ui_primitives.rs" architecture.md
require_grep "ui_widgets.rs" architecture.md

# Cleaned source tree.
if find firmware/assistant-rs/components -type d -name '_archive_*' | grep -q .; then
  fail "component _archive_* directories remain"
fi
require_absent_path tmp
require_absent_path firmware/assistant-rs/docs
require_absent_path docs/RELEASE_v0.1.36-r56-r2.md
require_absent_path docs/RELEASE_v1.0.0.md
require_absent_path docs/CHANGELOG.md
require_absent_path docs/USERGUIDE.md
require_absent_path firmware/assistant-rs/components/st77916_shim/idf_component.yml
require_absent_path firmware/assistant-rs/ASSISTANT_README.md
# v1.0.1-r14-r2: components_esp32s3.lock is generated by ESP-IDF component manager during build.
# Keep it ignored/untracked, but allow it during local post-build validation.
require_no_grep "jpeg_decoder.h" firmware/assistant-rs/components/st77916_shim/st77916_shim.c
require_no_grep "st77916_probe_sd_mjpeg_library" firmware/assistant-rs/components/st77916_shim/st77916_shim.c
require_no_grep "st77916_video_worker_start" firmware/assistant-rs/components/st77916_shim/st77916_shim.c
require_no_grep "st77916_mjpeg" firmware/assistant-rs/components/st77916_shim/include/st77916_shim.h
require_no_grep "esp_jpeg" firmware/assistant-rs/components/st77916_shim/CMakeLists.txt

# Docs point to current baseline.
require_grep "v1.0.1-r13" README.md
require_grep "v1.0.1-r13" architecture.md
require_grep "v1.0.1-r13" docs/RELEASE_v1.0.1.md
require_grep "RAW-V1-0-1-R14-CLEAN-README" README.md
require_grep "RAW-V1-0-1-R14-CLEAN-ARCHITECTURE" architecture.md

main_lines=$(wc -l < firmware/assistant-rs/src/main.rs | tr -d ' ')
shim_lines=$(wc -l < firmware/assistant-rs/components/st77916_shim/st77916_shim.c | tr -d ' ')

echo "Assistant current consolidated validation: OK"
echo "v1.0.1-r13 accepted Internet Radio baseline: OK"
echo "v1.0.1-r14 source directory cleanup: OK main_lines=${main_lines} st77916_shim_lines=${shim_lines}"

# RAW-V1-0-1-R14-R2-GENERATED-COMPONENTS-LOCK-VALIDATOR-REPAIR
python3 - "$ROOT" <<'PY_V1_0_1_R14_R2_LOCK'
from pathlib import Path
import subprocess
import sys

root = Path(sys.argv[1])
lock_rel = "firmware/assistant-rs/components_esp32s3.lock"
lock = root / lock_rel
gitignore = root / ".gitignore"

def fail(msg):
    print(f"CURRENT VALIDATION FAILED: {msg}", file=sys.stderr)
    raise SystemExit(1)

if lock.exists():
    if gitignore.exists() and lock_rel not in gitignore.read_text(errors="replace"):
        fail(f"generated lock exists but is not ignored: {lock_rel}")

    if (root / ".git").exists():
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", lock_rel],
            cwd=root,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if tracked.returncode == 0:
            fail(f"generated lock is tracked by git; run: git rm -f --cached {lock_rel}")

print("v1.0.1-r14-r2 generated components lock validator repair: OK")
PY_V1_0_1_R14_R2_LOCK
